{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "platform-service.fullname" . }}-network-policy
  labels:
    app: {{ required "app is required" .Values.app }}
{{ include "kubeit.tags" . | trim | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app }}
      version: {{ .Values.version }}
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          istio: pilot
      namespaceSelector:
        matchLabels:
          istio-operator-managed: Reconcile
{{- if .Values.gateway.exposeService }}
  - from:
    - podSelector:
        matchLabels:
          istio: ingressgateway
      namespaceSelector:
        matchLabels:
          istio-operator-managed: Reconcile
{{- end }}
{{- range .Values.networkPolicy.appsAllowedAccess }}
  - from:
    - podSelector:
        matchLabels:
          app: {{ . }}
    ports:
    - protocol: TCP
      port: {{ $.Values.image.containerPort }}
{{- end }}
{{- end }}
