{{/*
Create the name of the service to use
*/}}
{{- if not .Values.deploymentOnly -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-service.serviceName" . }}
  labels:
    app.kubernetes.io/name: {{ include "platform-service.name" . }}
    helm.sh/chart: {{ include "platform-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ required "app is required" .Values.app }}
{{ include "kubeit.tags" . | trim | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ required "service.port must be specified" .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "platform-service.name" . }}
    app: {{ .Values.app }}
{{- end}}
