{{/*
Create the name of the service account to use
*/}}
{{- define "platform-service.serviceAccountName" -}}
{{- if .Values.serviceAccount.useReleasePrefix -}}
    {{- .Release.Name -}}-
{{- end -}}
{{- if .Values.serviceAccount.create -}}
    {{ default .Values.app .Values.serviceAccount.name }}
{{- else -}}
    {{ default "default" .Values.serviceAccount.name }}
{{- end -}}
{{- end -}}
{{- if not .Values.deploymentOnly -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform-service.serviceAccountName" . }}
  labels:
{{ include "appLabels" . | trim | indent 4 }}
{{- end}}
{{- end}}
